// fodinhaStyles.tsx
import { StyleSheet, Platform } from "react-native";
import { BOTTOM_INSET, STATUSBAR_HEIGHT, width } from "./constants.ts";

export const styles = StyleSheet.create({
    backgroundContainer: {
        flex: 1,
        width: '100%',
        backgroundColor: '#1A2C42',
    },
    image: {
        marginTop: 8,
        marginLeft: -2,
        width: 50,
        height: 24,
        resizeMode: 'contain'
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(20, 30, 40, 0.85)',
    },
    mainContainer: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: STATUSBAR_HEIGHT,
    },
    loadingContent: {
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 18,
        fontWeight: '500',
        color: '#FFFFFF',
        letterSpacing: 0.5,
    },
    headerContainer: {
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    contentContainer: {
        flex: 1,
        padding: 16,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: -0.5,
    },
    headerButtons: {
        flexDirection: 'row',
    },
    headerButton: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 8,
        marginLeft: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    headerButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    disabledButton: {
        opacity: 0.4,
    },
    setupContainer: {
        marginBottom: 20,
        padding: 16,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    setupTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 16,
        textAlign: 'center',
    },
    addPlayerContainer: {
        flexDirection: 'row',
        marginBottom: 16,
    },
    playerInput: {
        flex: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        color: '#FFFFFF',
        fontSize: 16,
        marginRight: 8,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    addPlayerButton: {
        backgroundColor: '#3498db',
        borderRadius: 8,
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        ...(Platform.OS === 'ios' ? {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
        } : {
            elevation: 3,
        }),
    },
    startGameButton: {
        backgroundColor: '#2ecc71',
        borderRadius: 8,
        paddingVertical: 14,
        alignItems: 'center',
        ...(Platform.OS === 'ios' ? {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
        } : {
            elevation: 3,
        }),
    },
    startGameButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
    },
    playersContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    playerCard: {
        width: '48%',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        ...(Platform.OS === 'ios' ? {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 3,
        } : {
            elevation: 2,
        }),
    },
    eliminatedPlayerCard: {
        opacity: 0.6,
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    playerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    playerName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
        flex: 1,
    },
    removePlayerButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(231, 76, 60, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    livesContainer: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    playerActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    decreaseButton: {
        flex: 1,
        backgroundColor: 'rgba(231, 76, 60, 0.8)',
        borderRadius: 8,
        paddingVertical: 8,
        alignItems: 'center',
        marginRight: 4,
    },
    increaseButton: {
        flex: 1,
        borderRadius: 8,
        paddingVertical: 8,
        alignItems: 'center',
        marginLeft: 4,
    },
    actionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    eliminatedBadge: {
        backgroundColor: 'rgba(231, 76, 60, 0.8)',
        borderRadius: 8,
        paddingVertical: 8,
        alignItems: 'center',
        marginTop: 12,
    },
    eliminatedText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    winnerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(20, 30, 40, 0.9)',
        zIndex: 1000,
        elevation: 10,
    },
    winnerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: STATUSBAR_HEIGHT,
        paddingBottom: BOTTOM_INSET,
        paddingHorizontal: 20,
    },
    winnerCard: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 20,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
        overflow: 'hidden',
        ...(Platform.OS === 'ios' ? {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.3,
            shadowRadius: 16,
        } : {
            elevation: 10,
        }),
    },
    winnerHeader: {
        width: '100%',
        backgroundColor: '#1A2C42',
        paddingVertical: 20,
        paddingHorizontal: 24,
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    winnerTitle: {
        fontSize: 26,
        fontWeight: '800',
        color: '#FFFFFF',
        letterSpacing: -0.5,
    },
    winnerBody: {
        width: '100%',
        padding: 24,
        alignItems: 'center',
    },
    winnerLivesContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    winnerLivesText: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1A2C42',
        marginLeft: 12,
    },
    winnerStatsContainer: {
        backgroundColor: 'rgba(26, 44, 66, 0.1)',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        marginBottom: 10,
        width: '100%',
        alignItems: 'center',
    },
    winnerStatsText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1A2C42',
    },
    winnerActions: {
        width: '100%',
        padding: 24,
        paddingTop: 0,
    },
    newGameButton: {
        backgroundColor: '#1A2C42',
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderRadius: 14,
        width: '100%',
        alignItems: 'center',
        marginBottom: 12,
        ...(Platform.OS === 'ios' ? {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
        } : {
            elevation: 3,
        }),
    },
    newGameButtonText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 18,
    },
    resetButton: {
        backgroundColor: 'transparent',
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderRadius: 14,
        width: '100%',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#e74c3c',
    },
    resetButtonText: {
        color: '#e74c3c',
        fontWeight: '700',
        fontSize: 18,
    },
    setupInfo: {
        fontSize: 16,
        color: '#FFFFFF',
        opacity: 0.8,
        marginBottom: 16,
        textAlign: 'center',
    },
    playersList: {
        marginTop: 16,
        marginBottom: 16,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 8,
        padding: 12,
    },
    playersListTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    playerListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    playerListName: {
        fontSize: 16,
        color: '#FFFFFF',
        flex: 1,
    },
});
